// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdRrDa7RxKGRD7aS9D0x2peSyOQ3oXlbQ',
    appId: '1:1018811833050:web:c3367d736a7b732a04a3e3',
    messagingSenderId: '1018811833050',
    projectId: 'to-do-ufpso',
    authDomain: 'to-do-ufpso.firebaseapp.com',
    storageBucket: 'to-do-ufpso.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChOlEVDOv3t4ZDvlITIlcXU-5-fQn5SUA',
    appId: '1:1018811833050:android:d47e5489e8bfeba304a3e3',
    messagingSenderId: '1018811833050',
    projectId: 'to-do-ufpso',
    storageBucket: 'to-do-ufpso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA08HenV0tw0vbLuEY79LDQ6bPYK1Obcdk',
    appId: '1:1018811833050:ios:ec3dc582fba4d45004a3e3',
    messagingSenderId: '1018811833050',
    projectId: 'to-do-ufpso',
    storageBucket: 'to-do-ufpso.firebasestorage.app',
    iosBundleId: 'com.example.toDoUfpso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA08HenV0tw0vbLuEY79LDQ6bPYK1Obcdk',
    appId: '1:1018811833050:ios:ec3dc582fba4d45004a3e3',
    messagingSenderId: '1018811833050',
    projectId: 'to-do-ufpso',
    storageBucket: 'to-do-ufpso.firebasestorage.app',
    iosBundleId: 'com.example.toDoUfpso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdRrDa7RxKGRD7aS9D0x2peSyOQ3oXlbQ',
    appId: '1:1018811833050:web:c336ee3ee55a509804a3e3',
    messagingSenderId: '1018811833050',
    projectId: 'to-do-ufpso',
    authDomain: 'to-do-ufpso.firebaseapp.com',
    storageBucket: 'to-do-ufpso.firebasestorage.app',
  );
}
